version: "3"

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - my_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]


volumes:
  my_db: