version: "3"

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - my_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]

  backend:
    image: kcoursedocker/task-9.2-back:latest
    environment:
      PG_HOST: database
      PG_NAME: my_db
      PG_USER: admin
      PG_PASSWORD: admin
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: kcoursedocker/task-9.2-front:latest
    ports:
      - 127.0.0.1:80:80
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  backend-migrations:
    image: kcoursedocker/task-9.2-back:latest
    environment:
      PG_HOST: database
      PG_NAME: my_db
      PG_USER: admin
      PG_PASSWORD: admin
    command: bash -c "make migrate"
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  backend-superuser:
    image: kcoursedocker/task-9.2-back:latest
    environment:
      PG_HOST: database
      PG_NAME: my_db
      PG_USER: admin
      PG_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: user
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: kov.andrey7@yandex.ru
    command: bash -c "make create-superuser"
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started
      backend-migrations:
        condition: service_started


volumes:
  my_db:


